{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "web14-app.name" . }}-monitor
  namespace: {{ .Values.namespace }}
  labels:
    release: monitoring
    {{- include "web14-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "web14-app.name" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.interval }}
{{- end }}