apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: state-230489-v14
  labels:
    app: redis
    org.bstu.owner: Siarhei-0788
    org.bstu.student.slug: as576-230489-v14
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis