apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: state-230489-v14
  labels:
    org.bstu.owner: Siarhei-0788
    org.bstu.student.slug: as576-230489-v14
type: Opaque
data:
  redis-password: cGFzc3dvcmQxMjM=  # "password123" в base64