apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: state-230489-v14
  labels:
    app: redis
    org.bstu.student.fullname: Pachko-Sergei-Alexandrovich
    org.bstu.student.id: "230489"
    org.bstu.group: AS-576
    org.bstu.variant: "14"
    org.bstu.course: RSIOT
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        args: ["--requirepass", "password123"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - password123
            - ping
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - password123
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        org.bstu.owner: Siarhei-0788
        org.bstu.student.slug: as576-230489-v14
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi